system:
  name: Asteroid
  strategy: global
  services:
  - AsteroidService
  access:
  - world
  - resources

---
system:
  name: Ship
  strategy: global
  services:
  - ShipService
  - ControllerService
  - InputService
  access:
  - world
  - resources