type:
  name: ControllerService
  include: "src/services/controller_service.h"

---

type:
  name: InputService
  include: "src/services/input_service.h"

---

type:
  name: PainterService
  include: "src/services/painter_service.h"

---
type:
  name: ShipService
  include: "src/services/ship_service.h"

---

type:
  name: AsteroidService
  include: "src/services/asteroid_service.h"