weapons:
  - id: laser
    projectileImage: smallbluelaser.png
    radius: 1
    mass: .01
    damping: 0
    projectileLifetime: 4
    cooldown: .2
    speed: 750
    physicalDamage: 10
    energyDamage: 0

...